#!/bin/bash
links="http://www.kangle.info"
files="/root/s-hell"
file2="/root/s-hell/log"
file3="/root/hl-tmp"
rm -rf /usr/bin/kangle
rm -rf kanglesh*
rm -rf kangle*
if [ ! -d "$files" -a "$file2" -a "$file3" ];
then
mkdir $files;
chmod 755 $files;
mkdir $file2;
chmod 755 $file2;
mkdir $file3;
chmod 755 $file3;
fi

cd $file3
rm -rf $files/config
wget -q $links/config -O $files/config
wget -q $links/main.sh -O main.sh
cp -f main.sh /usr/bin/kangle
chmod 755 /usr/bin/kangle
sh main.sh
